config/routes.rb
Battleship::Application.routes.draw do
  get "game/new", :as => 'new_game'

  match "game/play", :as => 'play_game'

  get "game/update_grid", :as => 'update_grid'

  root :to => "game#index"
end

app/models/game.rb
require 'net/http'
require 'uri'
class Game < ActiveRecord::Base
  attr_accessible :game_status, :p45_game_id, :name, :email
  
  validates :name, :email, :presence => true

  has_many :ships
  has_many :salvos

  after_create :create_fleet # add the opponent's (p45's) ships for tracking
  after_create :register_game # register the game with p45

  def sink_ship(name)
    ship_to_sink = ships.alive.where(:name => name).first
    ship_to_sink.sink! if ship_to_sink
  end

  def nuke(x,y)
    params = {:id => p45_game_id, :x => x.to_i, :y => y.to_i}
    #resp = Net::HTTP.post_form(URI.parse(battle_host + "nuke"), params)
    resp = post_to_battle_host("/nuke", params)
    if resp.code.to_i == 200
      data = JSON.parse(resp.body)
      salvos.fire(x,y,data["status"],data["sunk"]) if data["status"]
      salvos.received_enemy_fire(data["x"], data["y"]) if data["x"] and data["y"] 
      # update game status when needed
      update_attribute(:game_status, data["game_status"]) if data["game_status"]
      update_attribute(:game_status, data["prize"]) if data["prize"]
    else
      raise "Error nuking: #{resp.body}"
    end
  end

  # play the move
  def play_move(coords={})
    unless game_status
      if x = coords[:x] and y = coords[:y]
        nuke(x,y)
      else
        nuke(*salvos.next_best_shot)
      end
    end
  end

  def game_over?
    !game_status.blank?
  end
  
  private 

  def register_game
    params = {:name => name, :email => email}
    #resp = Net::HTTP.post_form(URI.parse(battle_host + "register"), params.to_json)
    resp = post_to_battle_host("/register", params)
    if resp.code.to_i == 200
      data = JSON.parse(resp.body)
      logger.debug "Registered game ... data: #{data.inspect}"
      logger.info "Registered game successfully: #{data["id"]}" 
      update_attribute(:p45_game_id, data["id"])
      salvos.received_enemy_fire(data["x"], data["y"]) if data["x"] and data["y"]
    else
      raise "Error registering game: #{resp.body}"
    end
  end

  def post_to_battle_host(path, params)
    req = Net::HTTP::Post.new(path) #, initheader = {'Content-Type' =>'application/json'})
    req.body = params.to_json
    resp = Net::HTTP.new(battle_host).start{|http| http.request(req)}
  end

  def battle_host
    "battle.platform45.com"
  end

  # generate the 7 ships to track p45's fleet
  def create_fleet
    # name => length
    [{"Carrier"     => 5}, {"Battleship" => 4}, {"Destroyer"   => 3},
     {"Submarine"   => 2}, {"Submarine"  => 2}, {"Patrol Boat" => 1},
     {"Patrol Boat" => 1}].each do |ship_info|
      ships.create(:name => ship_info.keys.first, :length => ship_info.values.first)
    end
  end
end

app/models/salvo.rb
class Salvo < ActiveRecord::Base
  attr_accessible :error, :game_id, :status, :x, :y, :enemy, :hit, :sunk
  belongs_to :game

  after_create :sink_related

  scope :success, where(:hit => true)
  scope :enemy, where(:enemy => true)
  scope :ours, where(:enemy => false)
  scope :sunk, where("sunk is not null")
  scope :not_sunk, where("sunk is null")
  scope :missed, where(:status => "miss")
  scope :hit, where(:status => "hit")
  scope :non_sunk_hit, hit.not_sunk  # hits to focus on when determining next nuke coords

  def self.next_best_shot
    if non_sunk_hit.count > 0 and (best_selection = (all_surrounding_coords & available_coords)).any?
      # TODO consider shots following a path, for example, dont hunt in the y direction ...
      # TODO ... when we have two consecutive hits in the y direction
      # let's knock out ships that we have hits on
      return best_selection.first
    else
      # ok, guess we are going to pick a random shot out of available grid spaces
      return available_coords.sample
    end
  end

  # the coords surrounding our hits (non sunk) 
  def self.all_surrounding_coords
    ours.non_sunk_hit.map(&:surrounding_coords).flatten(1)
  end

  def self.available_coords
    all_coords = coords_for_grid(10,10)
    all_coords - ours.map(&:coords)
  end

  def self.fire(x,y,status,sunk=nil)
    failed_nuke(x,y,status) if status == "miss"
    successful_nuke(x,y,status,sunk) if status == "hit"
  end
  
  def self.received_enemy_fire(x,y)
    create(:x => x, :y => y, :enemy => true)
  end

  def coords
    [x,y]
  end

  # the four surrounding points (may be out of bounds)
  def surrounding_coords
    [[x+1,y], [x-1,y], [x,y+1], [x,y-1]]
  end

  private 

  # salvos consecutive along the same access as this salvo and that have an appropriate count
  def related_salvos(shots_needed)
    logger.debug "Looking for other shots to 'sink'"
    # find x and y salvos to compare with
    xs = game.salvos.ours.where(:x => x, :y => (y-shots_needed..y+shots_needed))
    ys = game.salvos.ours.where(:y => y, :x => (x-shots_needed..x+shots_needed))
    logger.debug "x direction 1: #{xs.inspect}"
    logger.debug "y direction 1: #{ys.inspect}"
    # look into the salvos and find the consecutive ones for each direction
    consecutive_xs = ys.map(&:x).sort.groupulate.find{|xss| xss.include?(x)}
    consecutive_ys = xs.map(&:y).sort.groupulate.find{|yss| yss.include?(y)}
    logger.debug "consecutive_x direction: #{consecutive_xs.inspect}"
    logger.debug "consecutive_y direction: #{consecutive_ys.inspect}"
    # update x's and y's based on the consecutive selection
    xs = game.salvos.ours.where(:x => x, :y => consecutive_ys)
    ys = game.salvos.ours.where(:y => y, :x => consecutive_xs)
    logger.debug "x direction 2: #{xs.inspect}"
    logger.debug "y direction 2: #{ys.inspect}"
    
    # figure out which salvos to focus on
    salvos = xs.count >= shots_needed ? xs : ys
    logger.debug "Determined salvos to be #{salvos.inspect}"
    salvos
  end

  # sink related shots so that we can ignore them when finding best coord to play
  def sink_related
    unless sunk.blank?
      # update :sunk for all shots associated with this shot
      shots_needed = game.ships.find_by_name(sunk).length
      logger.debug "need #{shots_needed} shots to sink the #{sunk}"
      # only need to look for others if we have shots needing updating
      if shots_needed > 1
        salvos = related_salvos(shots_needed)
        salvos.each{|s| s.update_attribute(:sunk, sunk)}
        return
      end
    end
  end

  def self.failed_nuke(x,y,status)
    logger.info "\033[0;31mFailed nuke - x: #{x}, y: #{y}\033[0;37m"
    create(:x => x, :y => y, :hit => false, :status => status)
  end
  
  def self.successful_nuke(x,y,status,sunk=nil)
    logger.info "\033[0;32mSuccessful nuke - x: #{x}, y: #{y}\033[0;37m"
    logger.info "\033[0;32mSunk one - #{sunk}\033[0;37m" if sunk
    create(:x => x, :y => y, :hit => true, :status => status, :sunk => sunk)
  end
  
  def self.coords_for_grid(num_x, num_y)
    coords = []
    num_x.times do |x|
      num_y.times do |y|
        coords << [x,y]
      end
    end
    coords
  end
end

app/models/ship.rb
class Ship < ActiveRecord::Base
  attr_accessible :game_id, :name, :length
  belongs_to :game

  scope :alive, where(:sunk => false)
  scope :sunk, where(:sunk => true)

  def sink!
    update_attribute(:sunk, true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/game_controller.rb
class GameController < ApplicationController

  def index
    if params[:game_over]
      game = Game.find(params[:game_over])
      flash.now[:notice] = "You Won ... congrats!" if game.game_status != "lost"
      flash.now[:notice] = "You Lost ... sorry :(" if game.game_status == "lost"
    end
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def play
    if params[:id]
      @game = Game.find(params[:id])
    else
      @game = Game.create(params[:game])
    end
    @play_manually = params[:manually] == "false" ? false : true # default to manually
    @game.play_move unless @play_manually
  end

  def update_grid
    @game = Game.find(params[:id])
    @game.play_move(:x => params[:x], :y => params[:y])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/game/_grid.html.haml
= heading
%table
  -10.times do |y|
    %tr
      -10.times do |x|
        -if shots.map(&:coords).include? [x,y]
          - shot = shots.find{|s| s.coords == [x,y]}
          %td{:class => shot.hit? ? "hit#{shot.sunk.blank? ? "" : " sunk"}" : "miss"}
        -else
          %td
            =link_to "", update_grid_path(:id => @game.id, :x => x, :y => y), :title => "Play x:#{x}, y:#{y}", :remote => true

app/views/game/index.html.haml
%h1 Games

=link_to "New Game", new_game_path

%table
  %thead
    %tr
      %th Name
      %th Email
      %th Status
      %th
  %tbody
    - @games.each do |game|
      %tr
        %td=game.name
        %td=game.email
        %td=game.game_status || "Playing"
        %td=link_to "View", play_game_path(:id => game.id)

app/views/game/new.html.haml
%h1 Start a new Game
=form_for @game, :url => play_game_path do |f|
  =f.label :name
  =f.text_field :name
  %br
  =f.label :email
  =f.text_field :email
  %br
  =f.submit "Play"

app/views/game/play.html.haml
%h1 Playing Game

.grid#enemy_grid
  =render "grid", :heading => "Their Side:", :shots => @game.salvos.ours
 
.grid#friendly_grid
  =render "grid", :heading => "Your Side:", :shots => @game.salvos.enemy
  
#legend
  %h3 Legend
  .sunk Sunk!
  .hit Hit
  .miss Miss
  .unknown Unknown
  %br
  - unless @game.game_over?
    - if @play_manually
      = link_to "Auto Play", play_game_path(:id => @game, :manually => false)
    - else
      = link_to "Manual Play", play_game_path(:id => @game, :manually => true)

= content_for :head do
  = stylesheet_link_tag "play"
  - unless @game.game_over? or @play_manually  # don't need to update
    = javascript_include_tag 'jquery.periodicalupdater', 'play'
    :javascript
      $(document).ready(function() {
        $.PeriodicalUpdater("#{update_grid_path}", {
          method: 'get',
          data: {id: "#{@game.id}"},
          minTimeout: 1500,
          maxTimeout: 4000
        });
      });

app/views/game/update_grid.js.haml
- if @game.game_over?
  window.location.href = "#{root_url(:game_over => "#{@game.id}")}";
- else
  $('#friendly_grid').html("#{escape_javascript(render 'grid', :heading => "Your Side:", :shots => @game.salvos.enemy)}");
  $('#enemy_grid').html("#{escape_javascript(render 'grid', :heading => "Their Side:", :shots => @game.salvos.ours)}");

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Battleship", root_path, :class => 'brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Battleship"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer